apiVersion: v1
kind: Service
metadata:
  name: spring-web-svc
spec:
  selector:
    app: spring-web
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080


